# Generated by Django 5.2.8 on 2025-12-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(editable=False, max_length=150, verbose_name='Название'),
        ),
    ]
