# Generated by Django 5.2.8 on 2025-12-02 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Данное поле заполняется автоматически', verbose_name='Короткая ссылка')),
                ('formula', models.CharField(max_length=50, verbose_name='Формула')),
                ('description_1', models.TextField(blank=True, null=True, verbose_name='Первая часть описания')),
                ('description_2', models.TextField(blank=True, null=True, verbose_name='Вторая часть описания')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
