# Generated by Django 5.2.8 on 2025-12-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Первая часть описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_1_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Первая часть описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Вторая часть описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_2_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Вторая часть описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
