# Generated by Django 5.2.8 on 2025-12-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_description_1_ru_product_description_1_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_1_en',
            field=models.TextField(blank=True, null=True, verbose_name='Первая часть описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Вторая часть описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
